apps/post/urls.py
from django.contrib import admin
from django.urls import path
from apps.post import views
# from apps.post.views import AddPost

urlpatterns = [
    path('post/', views.posts, name='posts'),
    path('post/get/<int:post_id>/', views.comments, name='comments'),

    # path('postAdd/<int:user_id>/', AddPost.as_view()),
    path('hello', views.hello, name='hello'),
    path('chek_username', views.chek_username, name='chek_username'),
    path('check_email', views.check_email, name='check_email'),
    path('post/search/', views.search, name='search'),
    path('post/addlike/<int:post_id>/', views.addlike, name='addlike'),
    # path('post/addlike/', views.addlike, name='addlike')



]

posts/urls.py
from django.contrib import admin
from django.urls import path, include

from apps.post import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.post.urls')),
    path('', include('apps.register.urls')),
    path('', include('apps.userProfile.urls')),
    path('', views.home, name='home')
]

apps/post/models.py
from django.db import models

from apps.userProfile.models import UserModel


# Create your models here.


class Post(models.Model):
    author = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    text = models.TextField(max_length=300)
    like = models.IntegerField(default=0)
    dislike = models.IntegerField(default=0)
    create_data = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text
    def __str__(self):
        return str(self.id)


class PostComments(models.Model):
    author_comment = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    post_coment = models.ForeignKey(Post, on_delete=models.CASCADE)
    text_coment = models.TextField(max_length=300)
    create_data = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.author_comment.username


class Likes(models.Model):
    author = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    likes= models.IntegerField(default=0)
    dislikes= models.IntegerField(default=0)

    def __str__(self):
        return str(self.likes)

apps/post/forms.py
from django.forms import ModelForm

from apps.post.models import Post, PostComments


class PostAddForm(ModelForm):
    class Meta:
        model = Post
        fields = ['text']

class CommentFormAdd(ModelForm):
    class Meta:
        model = PostComments
        fields = ['text_coment',]

apps/post/views.py
import json

from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import redirect
from django.urls import reverse
from django.shortcuts import render, HttpResponse, render_to_response, get_object_or_404, HttpResponseRedirect
from django.template.loader import render_to_string
from django.views import View
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404
from apps.post.forms import PostAddForm, CommentFormAdd
from apps.post.models import Post, PostComments, Likes
from apps.userProfile.models import UserModel


# Create your views here.
def hello(rqequest):
    return render_to_response('response.html', {'variable': 'world'})


def home(request):
    # print('kkkkkkkkkkkk', user)

    if authenticate != False:
        print('kkkkkkkkkkkkkkkkkkkkkkkkk', request.user.id)

        # return HttpResponseRedirect(reverse('posts', args=[request.user.id]))
        return redirect('signin')
    else:
        return render(request, 'home.html', locals())


@login_required(login_url='/login')
def posts(request,):
    form1 = PostAddForm(request.POST)
    if request.POST and form1.is_valid():
        # author = request.POST['author']
        post = form1.save(commit=False)
        post.author_id = request.user.id
        post.save()
    postlist = Post.objects.all().order_by('-create_data')
    paginator = Paginator(postlist, 5)
    page = request.GET.get('page')
    post = paginator.get_page(page)
    context = {'posts': post, 'form1': form1, }
    return render(request, 'posts.html', context)

@login_required(login_url='/login')
def comments(request, post_id=1):
    form = CommentFormAdd(request.POST)
    if request.POST and form.is_valid():
        author_comment = request.POST['author_comment']
        post_coment = request.POST['post_coment']
        comment = form.save(commit=False)
        comment.post_coment_id = int(post_coment)
        comment.author_comment_id = author_comment
        comment.save()
    else:
        form = CommentFormAdd()
    try:
        post = Post.objects.get(id=post_id)
    except AttributeError:
        return HttpResponse('no posts')
    try:
        comment = PostComments.objects.filter(post_coment_id=post_id).order_by('-create_data')
    except AttributeError:
        return HttpResponse('no posts')
    comentlist = [comment]
    for comentslenght in comentlist:
        try:
            comentCount = len(comentslenght)
            if comentCount < 1:
                comentCount = 0
        except:
            comentCount = 0

    context = {'posts': post, 'post':post, 'comments': comment, 'comentCount': comentCount, 'form': form}
    return render(request, 'postcoments.html', context)

@login_required(login_url='/login')
def search(request):
    querry = request.GET.get('q')
    search_list = list(Post.objects.filter(
        Q(text__icontains=querry)
        # Q(author__icontains=querry)
    ).order_by('-create_data'))
    # paginator = Paginator(search, 2)
    # page = request.GET.get('page')
    # search_list = paginator.get_page(page)
    return_str = render_to_string('ajaxsearch.html', {'search_list': search_list, 'q':querry,})
    return HttpResponse(json.dumps(return_str), content_type='application/json')
    # return render_to_response('home.html', {'search_list': search_list})
@login_required(login_url='/login')
def addlike(request, post_id):
# def addlike(request):
    user =  request.user.id
    post = post_id
    nolike = Likes.objects.filter(author_id=user, post_id=int(post))
    if nolike:
        like =Likes.objects.get(author_id=user, post_id=int(post))
        like.delete()
        postLike = Post.objects.get(id=int(post))
        postLike.like -= 1
        postLike.save()
        return HttpResponse('dislike')

    else:
        like =Likes.objects.create(author_id=user, post_id=int(post))
        postLike = Post.objects.get(id=int(post))
        postLike.like += 1
        postLike.save()
        like.likes  +=1
        like.save()
        return HttpResponse('like')
    # return render(request, 'posts.html')
    return HttpResponse('like')



def likecount(request):
    likelist = Likes.objects.filter(post_id=int(post))
    likes = [likelist]
    for likelenght in likes:
        try:
            likecount = len(likelenght)
            if likecount < 1:
                likecount = 0
        except:
            likecount = 0
    context = {'likecount':likecount}
    return render(request, 'posts.html', context)


# class AddPost(View):
#     def get(self, request, user_id):
#         user = get_object_or_404(Post, id=user_id)
#         form = PostAddForm(initial={
#             'user': user
#         })
#         print('krakadil')
#         return render(request, 'posts.html', {'user': user, 'form': form}, locals())
#         # return render(request, 'posts.html', locals())
#
#     def post(self, request, user_id):
#         if request.POST:
#             form = PostAddForm(request.POST or None)
#             if form.is_valid():
#                 post = form.save(commit=False)
#                 post.save()
#                 print(form)
#                 return render(request, 'posts.html', {'user': user, 'form': form}, locals())
#             else:
#                 form = PostAddForm()
#             return render(request, 'posts.html', {'user': user, 'form': form}, locals())


def chek_username(request):
    if request.GET:
        user_name = request.GET['username']
        users = UserModel.objects.filter(username=user_name)
        if users:
            return HttpResponse('no', content_type='text/html')
        else:
            return HttpResponse('ok', content_type='text/html')
    else:
        return HttpResponse('ok', content_type='text/html')


def check_email(request):
    if request.GET:
        email = request.GET['email']
        users_email = UserModel.objects.filter(email=email)
        if users_email:
            return HttpResponse('no', content_type='text/html')
        else:
            return HttpResponse('ok', content_type='text/html')
    else:
        return HttpResponse('ok', content_type='text/html')

templates/ajaxsearch.html
{# {% extends "posts.html" %} #}
{% load static %}
 {% block search %}

 <div class="comments-container">
     <h3>Results for " {{q}} ": Found {{ search_list|length }} Item</h3>
     <ul id="comments-list" class="comments-list">
         {% for post in search_list %}
             <div class="comment-main-level">
                 <!-- Avatar -->
                 {% if post.author.user_image %}

                     <div class="comment-avatar"><img src="/{{ post.author.user_image.url }}" alt=""></div>
                 {% else %}
                     <div class="comment-avatar"><img src="{% static 'images/userDefoultAvatar/Avatar.png' %}"
                                                      alt=""></div>
                 {% endif %}
                 <!-- Contenedor del Comentario -->
                 <div class="comment-box">
                     <div class="comment-head">
                         <h6 class="comment-name by-author"><a
                                 href="#">{{ post.author }}</a></h6>
                         <span>Post Created: {{ post.create_data }}</span>
                         <i class="fa fa-reply"></i>
                         <i class="fa fa-heart"></i>
                     </div>
                     <div class="comment-content">
                         {{ post.text }}
                     </div>
                  
                       <span id='likevalue' data='{{ post.id}}'><img src="{%static 'images/icon/like.png'%}" alt="Like" id='like' class="img-rounded center-block"><span ><small id="countlike{{post.id}}">{{post.like}}</small></span></span>

                    </a>
                 </div>

             </div>

             </li>
         {% endfor %}
       </ul>

         <!-- pagination div-->
        <!--  <div class="pagination">
               <span class="step-links">
                   {% if search_list.has_previous %}
                       <a href="?page=1">&laquo; first &nbsp;</a>
                       <a href="?page={{ search_list.previous_page_number }}">previous</a>
                   {% endif %}

                   <span class="current">
                       Page {{ search_list.number }} of {{ search_list.paginator.num_pages }}.
                   </span>

                   {% if post.has_next %}
                       <a href="?page={{ search_list.next_page_number }}">next &nbsp;</a>
                       <a href="?page={{ search_list.paginator.num_pages }}">last &raquo;</a>
                   {% endif %}
               </span>
           </div>  -->
         {% if not search_list %}
            <h3> No posts for this query. {{q}}</h3>
         {% endif %}

 </div>

 {% endblock search %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% block title %}
  <title>home</title>
{% endblock %}
<html>
<head>
    <meta charset="utf-8">

    <title>base</title>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css"
          integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">

</head>
<body style="background-color: #C9C2D0;">
      <span><a href="{%url 'posts'%}"><h3>Home</h3></a></span>

  {% block content %}

  {% endblock content %}
</body>
<script type="text/javascript" src="{% static 'js/search.js' %}"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js"
        integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4"
        crossorigin="anonymous"></script>


{% block js %}

{% endblock js %}
</html>

templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <h3>home page</h3>
    {% for result in search_list  %}
    <h3>{{result.text}}</h3><br>
      {# {{result.author}} #}
    {% endfor %}


{% endblock %}

{% block js %}
    <script type="text/javascript" src="{% static 'js/search.js' %}"></script>

{% endblock js%}

templates/postcoments.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
  <title>postComments</title>
{% endblock %}
{% block content %}
      <div class="">
          <h3> Logined width {{ request.user.username }}!</h3>
          <a href="{% url 'logout' %}">logauth</a>
      </div>
      <div class="comments-container">
          <ul id="comments-list" class="comments-list">
                  <div class="comment-main-level">
                      <!-- Avatar -->
                      {% if post.author.user_image %}
                          <div class="comment-avatar"><img src="/{{ post.author.user_image.url }}" alt=""></div>
                      {% else %}
                          <div class="comment-avatar"><img src="{% static 'images/userDefoultAvatar/Avatar.png' %}"alt=""></div>
                      {% endif %}
                      <!-- Contenedor del Comentario -->
                      <div class="comment-box">
                          <div class="comment-head">
                              <h6 class="comment-name by-author"><a
                                      href="#">{{ post.author }}</a></h6>
                              <span>Post Created: {{ post.create_data }}</span>
                              <i class="fa fa-reply"></i>
                              <i class="fa fa-heart"></i>
                          </div>
                          <div class="comment-content">
                              {{ post.text }}
                          </div>
                            <span class="glyphicon glyphicon-comment">
                              <input type="button" value="Comment {{ comentCount }}"  data-toggle="collapse" class='commentbtn'>
                            </span>
                            <span>
                              <span  id='likevalue' data='{{ post.id}}'><img src="{%static 'images/icon/like.png'%}" alt="Like" id='like' class="img-rounded center-block"><span ><small id="countlike{{post.id}}">{{post.like}}</small></span></span>
                            </span>
                            <span>
                              {# <a href="/post/addlike/{{post.id}}/"><img src="{%static 'images/icon/dislike1.png'%}" alt="Dislike" id='dislike' class="img-rounded center-block"></a>{{posts.dislike}} #}
                            </span>
                      </div>
                  </div>
                  <!-- Comment to Posts -->
                  <div class='comentIncoment'>

                      <ul class="comments-list reply-list">
                          {% for comment in comments %}
                              <li>
                                  <!-- Avatar -->
                                  {% if comment.author_comment.author.user_image %}
                                      <div class="comment-avatar"><img
                                              src="/{{ comment.author_comment.author.user_image.url }}" alt=""></div>
                                  {% else %}
                                      <div class="comment-avatar"><img
                                              src="{% static "/images/userDefoultAvatar/Avatar.png" %}" alt=""></div>
                                  {% endif %}
                                  <!-- Contenedor del Comentario -->
                                  <div class="comment-box">
                                      <div class="comment-head">
                                          <h6 class="comment-name"><a href="#">{{ comment.author_comment }}</a></h6>
                                          <span>{{ comment.create_data }}</span>
                                          <i class="fa fa-reply"></i>
                                          <i class="fa fa-heart"></i>
                                      </div>
                                      <div class="comment-content">
                                          {{ comment.text_coment }}
                                      </div>
                                  </div>
                              </li>
                          {% endfor %}
                      </ul>
                  </div>
                  {% if commentError %}
                    {{commentError}}
                  {% endif %}
                  </li>
              {# {% endfor %} #}
          </ul>
      </div>

      <div class="col-md-12 column">
        <form method="post">
            {% csrf_token %}
              <div class="col-md-8 col-md-offset-2 fieldWrapper form-group">

                  <select name="author_comment" required="" id="id_author_comment" style="display:none">
                      <option value="{{request.user.id}}">{{request.user.username}}</option>
                    </select>
                    <select name="post_coment" required="" id="id_post_coment" style="display:none">
                      <option value="{{posts.id}}"></option>
                    </select>
                    <div class="form-group">
                       <label for="comment">ADD Coment:</label>
                       <textarea class="form-control" name="text_coment" required="" cols="20" maxlength="300" id="id_text_coment" rows="4" maxlength="300" placeholder="Enter your comment her..."></textarea>
                    </div>
                  {# {{ form.text_coment}} #}

                  <input type="submit" name="" value="Add comment" class="btn btn-primary">
              </div>
          </form>
      </div>

      {% block js %}
          <script type="text/javascript" src="{% static 'js/jsajax.js' %}"></script>
          <script type="text/javascript" src="{% static 'js/myjs.js' %}"></script>
          <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
      {% endblock js %}


{% endblock %}

templates/posts.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}
  <title>post</title>
{% endblock %}
{% block content %}
    <div class="">
        <h3> Logined width {{ request.user.username }}!</h3>
        <a href="{% url 'logout' %}">logauth</a>
        <div >
          <form  action="search/" class="navbar-form navbar-left" id='search-form'>
                 <div class="form-group">
                   <button type="submit" class="btn btn-default btnSearch" id='searchPost'>Search</button>
                   <input type="text" class="search-input" placeholder="Search..." width="50px" name='q'>
                 </div>
          </form>
        </div><br>

    </div>
    <div class="col-md-12 column postAddClass">
        <form method="post">
          {% csrf_token %}
            <div class="col-md-8 col-md-offset-2 fieldWrapper form-group">
                <select name="author" required="" id="id_author" style="display:none">
                  <option for='author' value="{{request.user.id}}" type="hidden">{{request.user.username}}</option>
                </select>
                {# {{ form1.text }} #}
                <div class="form-group">
                   <label for="comment">ADD Post:</label>
                   <textarea class="form-control" name="text" required="" cols="20" maxlength="300" id="id_text" rows="4" placeholder="Enter your comment her..."></textarea>
                </div>
                <input type="submit" name="" value="Post" class="btn btn-primary">
            </div>
        </form>
    </div>

    {% block search %}

    <div class="posts">
          <!-- div vith ajax search  -->
    </div>
    {% endblock search %}
    <div class="comments-container divforpostsWiew">
        <ul id="comments-list" class="comments-list">
            {% for post in posts %}
                <div class="comment-main-level">
                    <!-- Avatar -->
                    {% if post.author.user_image %}
                        <div class="comment-avatar"><img src="/{{ post.author.user_image.url }}" alt=""></div>
                    {% else %}
                        <div class="comment-avatar"><img src="{% static 'images/userDefoultAvatar/Avatar.png' %}"alt=""></div>
                    {% endif %}
                    <!-- Contenedor del Comentario -->
                    <div class="comment-box">
                        <div class="comment-head">
                            <h6 class="comment-name by-author"><a
                                    href="#">{{ post.author }}</a></h6>
                            <span>Post Created: {{ post.create_data }}</span>
                            <i class="fa fa-reply"></i>
                            <i class="fa fa-heart"></i>
                        </div>
                        <div class="comment-content">
                            {{ post.text }}
                        </div>

                        {# <div class="container">#}
                        <!--  like button -->
                        <a href="/post/get/{{post.id}}">
                          <button type="button" class="btn btn-outline-secondary"name="button">Read more &raquo;</button>
                        </a>
                        {# <a href="/post/addlike/{{post.id}}/" id='likevalue'> <img src="{%static 'images/icon/like.png'%}" alt="Like" id='like' class="img-rounded center-block"></a>{{post.like}} #}
                        <span id='likevalue' data='{{ post.id}}'><img src="{%static 'images/icon/like.png'%}" alt="Like" id='like' class="img-rounded center-block"><span ><small id="countlike{{post.id}}">{{post.like}}</small></span></span>
                        {# <a href="/post/addlike/{{post.id}}/"><img src="{%static 'images/icon/dislike1.png'%}" alt="Dislike" id='dislike' class="img-rounded center-block"></a>{{post.dislike}} #}

                        {# </div>#}
                    </div>
                </div>
                </li>
            {% endfor %}

        </ul>
        <!-- pagination div -->
        <div class="pagination">
              <span class="step-links">
                  {% if posts.has_previous %}
                      <a href="?page=1">&laquo; first &nbsp;</a>
                      <a href="?page={{ posts.previous_page_number }}">previous</a>
                  {% endif %}

                  <span class="current">
                      Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
                  </span>

                  {% if posts.has_next %}
                      <a href="?page={{ posts.next_page_number }}">next &nbsp;</a>
                      <a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
                  {% endif %}
              </span>
          </div>

    </div>


    {% block js %}
        <script type="text/javascript" src="{% static 'js/jsajax.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/myjs.js' %}"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    {% endblock js %}


{% endblock content %}

templates/response.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <script type="text/javascript" src="{%static 'js/jsajax.js'%}">

    </script>
  </head>
  <body>
    <h1>Hello {{ variable }}, welcome to my awesome site</h1>
  </body>
</html>